### ISSUE TITLE
piece count inputs

### ISSUE THREAD

**Issue by ChrisWhittington** [dshawul/nn-train#1]
I'm finding get some sort of stable, or indeed any sensible value out of training to be quite tough. did you find adding piece type count difference to the value head inputs to be a help?

**Comment by dshawul** [comment]
Yes it did help me to add piece counts and attack tables especially when you have only a couple of million games for training. I have a branch that takes only alpha-zero like input planes (12 piece) planes, and it often produces weaker nets at the same number of games.

**Comment by ChrisWhittington** [comment]
Yup, I've been running training with differential piece counts since this morning. Better value metrics result.

Initial LR is a tricky one. Scorpio seems to be running cyclic learning over the length of each test suite, start 0.2 and dropping by power of 10 over four steps, if I read it correct. AZ and LC0 also seem to start training at LR 0.1 or 0.2.
My net is not as tall as those, so maybe that is a factor, but I find  if initial LR is anything above 0.02 learning gets often unstable and goes the wrong way. I'm resisting lower initial_lr because then the opportunity for later reduction schedules is reduced.
